name: Add label, assignee to every pr

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: "Add pull request labels and assignees"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NO: ${{ github.event.pull_request.number }}
          USER: ${{ github.actor }}
        run: |
          gh pr edit $PR_NO --add-label "enhancement"
          gh pr edit $PR_NO --add-assignee $USERS
