name: Every push to main, push to release for deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  push-to-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Create and push to release branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b release
          git push --force origin release
          - name: Create and push to release branch
      - name: Update develop branch
        run: |
          git checkout -b develop
          git push --force origin develop