name: Every push to main, push to release for deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push-to-release:
    runs-on: ubuntu-latest
    steps:
      - name: Push to release branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b release
          git push --force origin release